title: Ving's Notes
author:
  name: Ving
  email: viing937@gmail.com
description: You got this. Make it happen.

minima:
  social_links:
    twitter: viing937
    github: viing937

remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
