title: Ving's Notes
author: Ving
email: viing937@gmail.com
description: You got this. Make it happen.

twitter_username: viing937
github_username: viing937

theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-seo-tag
