title: Ving's Notes
author:
  name: Ving
  email: viing937@gmail.com
description: You got this. Make it happen.

minima:
  social_links:
    - { platform: twitter, user_url: "https://twitter.com/viing937" }
    - { platform: github, user_url: "https://github.com/viing937" }

remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
