syntax on

set cursorline
set shiftwidth=4
set clipboard=unnamed
set tabstop=4
set number
set expandtab
set nowritebackup
set noswapfile
set nobackup
set hlsearch
set ignorecase
set smartcase

noremap <CR> :nohlsearch<CR>
